### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#11]
I would like to be able to customize the error message. For example to be able to linking to a documentation in your project where it is explained how to write proper commits, or to give more details about what the whitelist/blacklist represent.

**Comment by bkuhlmann** [comment]
Are you wanting to wanting to bake that into the error messages displayed/printed in the build? You might want to take a look at the [severity](https://github.com/bkuhlmann/git-cop/compare/severity?expand=1) branch that I'm working on where I extract out the ability to leave issue (previously known as `error`) hints. The severity branch, BTW, is related to the [severity issue](https://github.com/bkuhlmann/git-cop/issues/6).

**Comment by bkuhlmann** [comment]
This issue has been resolved by this [pull request](https://github.com/bkuhlmann/git-cop/pull/17).

**Comment by Ana06** [comment]
@bkuhlmann I think you misunderstood me, I didn't mean the error warning thing, but to allow to have custom error messages. For example, to add a link to documentation and to clarify the errors with regular expressions. In my case I have this error message: 
`Commit Subject Prefix Error. Use: /\A(?!\s)(\[api\])?(\[backend\])?(\[ci\])?(\[dist\])?(\[doc\])?(\[webui\])? [a-zA-Z]/.`
and I would prefer having something like:
`Commit Subject Prefix Error. Tag your commit properly. See link_to_documentation.`


This could be configured with something like this (a `message` param):

```
:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :message: "Tag your commit properly. See link_to_documentation"
  :whitelist:
    - \A(?!\s)(\[api\])?(\[backend\])?(\[ci\])?(\[dist\])?(\[doc\])?(\[webui\])? [a-zA-Z]
```

**Comment by bkuhlmann** [comment]
The `:message` (or `:hint` as it's known internally) would replace the default text then? It would also probably need a string placeholder (i.e. `%s`) so regular expression output could be displayed in the feedback as it does currently (or not, in the case where you wouldn't want the regular expressions in the output at all).

What you're suggesting feels a lot like i18n support where, in this case, could be used as alternate/custom output.

The link to documentation, while I understand would be handy, worries me a bit since it could get out of date rather quickly. Would need to think about how that could be generated or updated in an automated fashion so this gem isn't hard to maintain.

**Comment by Ana06** [comment]
@bkuhlmann 

> The link to documentation, while I understand would be handy, worries me a bit since it could get out of date rather quickly. Would need to think about how that could be generated or updated in an automated fashion so this gem isn't hard to maintain.

well, my idea is just to allow the user to have his own error messages, so he could write whatever he want, documentation, explanation of what regular expression mean or any other thing that he think about. This was just an example of why this would be really useful.

> The :message (or :hint as it's known internally) would replace the default text then? It would also probably need a string placeholder (i.e. %s) so regular expression output could be displayed in the feedback as it does currently (or not, in the case where you wouldn't want the regular expressions in the output at all).

I would leave the name of the cop that is failing and replacing the rest of the current error message with the one provided by the user, if any.

> What you're suggesting feels a lot like i18n support where, in this case, could be used as alternate/custom output.

Not sure if I get what you exactly mean. What I suggest is just replace the current error message with the one provided by the user, without doing anything else. Just whatever the user introduced is what is rendered.

**Comment by bkuhlmann** [comment]
Yeah, that makes sense. I think that level of customization becomes more interesting if this gem needed i18n support (i.e. Internationalization). With i18n, one could provide translations in English, Spanish, German, etc. ...or even different versions of a specific language. With support like that, you could then customize any of the text output however you liked.

That said, not sure I want to support this yet. It's good that this gem is customizable as is but would like to wait and see if others have this issue before proceeding.

**Comment by Ana06** [comment]
@bkuhlmann 

> Yeah, that makes sense. I think that level of customization becomes more interesting if this gem needed i18n support (i.e. Internationalization). With i18n, one could provide translations in English, Spanish, German, etc. ...or even different versions of a specific language. With support like that, you could then customize any of the text output however you liked.

:+1: 

> That said, not sure I want to support this yet. It's good that this gem is customizable as is but would like to wait and see if others have this issue before proceeding.

Maybe leaving the issue open then?

What is the problem of supporting it? It is not something complicate to implement/support, right?

**Comment by bkuhlmann** [comment]
Let's leave the issue closed for now to maintain [Inbox Zero](http://www.43folders.com/izero) and keep the cognitive load low as possible. We can always search for this later if need be.

Adding i18n support would complicate the implementation and add more maintenance complexity. It'd be some effort to support so let's wait and see if the pain point grows in intensity before proceeding.
