### ISSUE TITLE
Travis support broken for PRs

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#24]
@bkuhlmann in https://github.com/bkuhlmann/git-cop/pull/20 you refactored the code in https://github.com/bkuhlmann/git-cop/pull/16 and broke the support for PRs as you remove a line that was needed.

You can see the difference in this two PR Travis builds:

With the last release: https://travis-ci.org/openSUSE/open-build-service/jobs/255177155
How it should look like: https://travis-ci.org/openSUSE/open-build-service/jobs/255986160

**Comment by Ana06** [comment]
I'll open a PR in a moment

**Comment by Ana06** [comment]
BTW, @bkuhlmann when refactoring my code you remove some comments that I think are important to explain why everything is needed. Because some of this things are needed because of unexpected Travis behavior and are not easy to guess, as some thing are not really documented, but I had to try them.

Would it be fine for you if I create a PR to add this comments again? :thinking:

**Comment by bkuhlmann** [comment]
In the future, could you use the GitHub issue template for these issues? It would be rather helpful to give them structure and make them easier to read. Thanks!

**Comment by bkuhlmann** [comment]
Yep, it's important to document the code. Most of the time this can be done within the commit message body but if the code is non-obvious then, yes, add comments to the code too. I tend to prefer the former unless the code can't speak to itself clearly enough.
