### ISSUE TITLE
Package of version 1.6.1 is not signed

### ISSUE THREAD

**Issue by koenrh** [bkuhlmann/git-cop#31]
## Overview

I just attempted to install version 1.6.1 (with the trust policy set to 'medium security'), and noticed that the latest version is not signed. The previous version (1.6.0) was signed.

## Steps to recreate

1. Download the developer's signing certificate: `curl https://www.alchemists.io/gem-public.pem -o git-cop.pem`.
2. Add the this trust anchor to the store: `gem cert --add git-cop.pem`.
3. Install the latest version (i.e. 1.6.1): `gem install git-cop -v 1.6.1 --trust-policy MediumSecurity`.
4. Note the warning message: `WARNING:  git-cop-1.6.1 is not signed`

**Comment by bkuhlmann** [comment]
Thanks for catching this! It looks like it was a bug in my build process. You are correct, it was not build with the proper signatures. I will get a fix out for this.

**Comment by bkuhlmann** [comment]
:information_source: This is fixed in [Version 1.6.2](https://github.com/bkuhlmann/git-cop/releases/tag/v1.6.2).
