### ISSUE TITLE
Verb tense for Commit Subject Prefix

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#38]
Currently Commit Subject Prefix only support a list of words. I think it is usual that you want to have the commit message starting by a verb in infinitive (or in past) and providing a complete list for that is complicate. What about adding an option to this cop to support this? The current list of words/regular expressions should still work.

**Comment by bkuhlmann** [comment]
Are you asking for the *Commit Subject Prefix* cop to support regular expressions? If so, it already has a whitelist which supports [Regular Expressions](https://github.com/bkuhlmann/git-cop#regular-expressions).

If you asking for changing the default words, then you might want to read the discussion in this [Issue](https://github.com/bkuhlmann/git-cop/issues/1) for more details.

**Comment by Ana06** [comment]
@bkuhlmann 

> Are you asking for the Commit Subject Prefix cop to support regular expressions? If so, it already has a whitelist which supports Regular Expressions.
>
>If you asking for changing the default words, then you might want to read the discussion in this Issue for more details.

No to both 🤣 I want to add an option to this cop to have the commit message starting by a verb in infinitive (or in past).

So for example:

```
:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :verb_tense: present
```

would only allow commits in present tense, such as "Update gem", while "Updated gem would fail. Or `:verb_tense: past` for just the oposite.

I want to keep the white list exactly as it is. So you could use either the `verb_tense` or the `white_list`, or both together. For example:

```
:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :verb_tense: present
  :whitelist:
    - [ci]
```

This will only allow commits in present tense, except if they start by `[ci]`.

**Comment by bkuhlmann** [comment]
What would be the value in supporting a `:verb_tense:` option if you could use a different whitelist? That would introduce feature complexity by managing a whitelist that would have to be inspected for present/past tense. It would also be hard for people to debug and reason about when things go wrong.

BTW, using tags or a kind of special metadata like `[ci]` in your commit subjects is generally not a good idea as that information should be metadata in the *body* of your commit message, not the subject. It's important to keep the subject lines clean and human readable.

**Comment by bkuhlmann** [comment]
Closing due to potential cognitive complexity for users of this gem.

**Comment by Ana06** [comment]
@bkuhlmann how would you support with a whitelist all possible verbs in infinitive tense? Internally we could use [a gem](https://github.com/rossmeissl/verbs) for this.

**Comment by bkuhlmann** [comment]
I'm not sure I would as supporting tense seems like an unnecessary complication. BTW, the gem you link to hasn't been updated in 8 years -- probably not a good idea to include in any project. :)
