### ISSUE TITLE
Refactor Commit Body Leading Space cop label/id.

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#4]
I think that was is called `leading space` should be called `line blank`. Both in the cop and in the documentation:

https://github.com/bkuhlmann/git-cop#commit-body-leading-space

**Comment by bkuhlmann** [comment]
Yeah, good catch. This should be fixed in the next major release. 😄

**Comment by bkuhlmann** [comment]
After giving this more thought and experimenting with different cop names, I'm going to close this issue. A couple reasons:

- Renaming this cop would mean adding deprecation warnings to the existing cop while promoting the new cop name (in order to not break backwards compatibility).
- Would require removing the original cop in the 2.0.0 version.
- The use of "Commit Body Leading Space" still feels like the right terminology. I tried the following but didn't like them much:
  - "Commit Body Line Space"
  - "Commit Body Preceding Space"
  - "Commit Body First Blank Line"

**Comment by Ana06** [comment]
> - Renaming this cop would mean adding deprecation warnings to the existing cop while promoting the new cop name (in order to not break backwards compatibility).

Is that really needed? If this is included in the release notes  if someone update the gem it is his responsibility to check if there is something new there and adapt his configuration file.

> - The use of "Commit Body Leading Space" still feels like the right terminology. I tried the following but didn't like them much:
>   - "Commit Body Line Space"
>   - "Commit Body Preceding Space"
>   - "Commit Body First Blank Line"

What about _Commit Separation Line_? As this line is to separate the title from the body.

I understand that it is work for something that is working, but I still think that the name is really confusing. When discussing with my team if introducing git-cop and what rules should be enabled, everybody agree they didn't want this cop because they had misunderstanding what it does. And I had write a description next to the name, but probably after reading the name they thought they didn't need the description. :rofl:

**Comment by bkuhlmann** [comment]
> Is that [backward compatibility] really needed?

Yep, it's important as this project adheres to [Semantic Versioning](https://github.com/bkuhlmann/git-cop#versioning).

> What about Commit Separation Line?

Naming, as they say, is one of the hardest things about writing good software. :) Yeah, this is really about finding a good name to what the blank line between subject and body is.

Would *Commit Body First Line* work?

**Comment by bkuhlmann** [comment]
Any feedback on this? Would either of the following be acceptable?

- *Commit Body First Line*
- *Commit Body Leading Line*

**Comment by Ana06** [comment]
@bkuhlmann 

> Any feedback on this? Would either of the following be acceptable?
> 
> - *Commit Body First Line*
> - *Commit Body Leading Line*

Both of them are better than the current name, but I like *Commit Body Leading Line* more :wink:

**Comment by bkuhlmann** [comment]
Awesome, thanks. Will add the new support with deprecation warnings soon.
