### ISSUE TITLE
Missing 2.0.0 release notes

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#41]
There are no Release notes for 2.0.0, so it is difficult to know what change.

There was important changes, like the ones mentioned here: https://github.com/bkuhlmann/git-cop#upgrade. But also the deprecation of https://github.com/bkuhlmann/git-cop/commit/d092bb05edb1ddd048025bc092ccf2275af4facd. :no_mouth:

**Comment by bkuhlmann** [comment]
This is [fixed](https://github.com/bkuhlmann/git-cop/releases/tag/v2.0.0) now. BTW, these changes can always be found in the [CHANGES](https://github.com/bkuhlmann/git-cop/blob/master/CHANGES.md#v200-2018-01-01) file as the entire history of the project is kept there.
