### ISSUE TITLE
Support Gitlab CI

### ISSUE THREAD

**Issue by wintersolutions** [bkuhlmann/git-cop#49]
## Overview
I want to a add a `git-cop` pipeline (job) to my project hosted on gitlab.com. I want to run the command `git-cop --police` in feature branches.

The pipeline breaks with the following error:

```
Git Cop: Invalid commit SHA: "fatal: ambiguous argument 'master..HEAD': unknown revision or path not in the working tree.". Unable to obtain commit details.
```
As a workaround I'm using:

```
module GitlabCI
  refine Git::Cop::Branches::Environments::Local do
    def shas
      repo.shas start: 'origin/master', finish: name
    end
  end
end
```
Or add the line:

```
git fetch origin master:master
```

to `.gitlab-ci.yml`.

So I guess a `Git::Cop::Branches::Environments::GitlabCI` class would be required. I could provide a PR with such a class. Would you welcome this addition?

There are issues/questions before I start tough:

* Gitlab offers a lot of customization and I could only guarantee that the implementation works with my workflow, it could break for other people that use different `git` strategies.
* Gitlab sets the very generic `CI` environment variable. So I was thinking that other CI environments could be detected as Gitlab by accident. We could check other environment variables but they could change in the future and may require future PRs.
* Is maintenance of a environment you obviously don't use a issue long term?

## Steps to Recreate
Create a (free) project on gitlab.com and add a pipeline calling `git-cop --police`.

**Comment by bkuhlmann** [comment]
Hey @wintersolutions. :wave: Thanks, yeah, a pull request for this would be great. I can work on setting up an account that would auto-build this too in the meantime (I think I have an old account for this). 

A `Git::Cop::Branches::Environments::GitLabCI` object and corresponding spec would be welcomed as well. :wink:

I'd like to address your three concerns mentioned above in the original order listed:

- That is definitely cause for concern. How hard would it be to research the possible combinations or are they truly infinite? If that's the case, this might not be a good solution and a plugin solution would have to be implemented for this gem. At least with a plugin solution, anyone could extend Git Cop for any custom environment without having to force this gem to support *all* environments (that's a bigger task, though).
- Yeah, we'd need an environment variable like `GITLAB` or `GITLABCI` to properly support this using the current implementation (see `Git::Cop::Branches::Feature#load_environment` for example). In Netlify's case, I had to open a pull request on their end to add the environment needed. That took some time which means it could take a while for GitLab to support this endeavor as well (assuming they are amicable to the idea).
- It is and has been a concern even when Travis CI support was first added. Luckily, these environments haven't changed much but doesn't mean that they will. GitLab sounds like it could be complex which would definitely be a maintenance burden.

All of this is to say that the idea is good but this might require some exploration/experimentation before submitting a solution that would work for *most* GitLab configurations (if that's even possible). :sweat_smile:

**Comment by wintersolutions** [comment]
I've been experimenting with my builds a little bit and I could not get the above workaround running for all of my use cases. I'm still trying to figure out which different behaviors gitlab has (everything regarding git pulls can be configured). I'll push a PR if I have a stable solution that would cover most use scases.

**Comment by bkuhlmann** [comment]
Sounds good. Another tactic might be to define a *preferred* solution (or the simplest solution that would work)? For instance, we could specify in the README what looks like. Example:

- Add `GITLAB=true` as an environment variable to your builds.
- Specify the Git clone command used for acquiring your repository code (this could be a full clone or a shallow clone (i.e. Travis CI), etc).

With that defined, we could then add a `Git::Cop::Branches::Environments::GitLab` object which knows how to diff the commits on the feature branch being built. The rest is up to the developer at that point but since GitLab behaves differently and requires a little extra setup on the developer than Circle CI, Netlify, and Travis CI that might be an OK compromise?

**Comment by bkuhlmann** [comment]
@wintersolutions Wanted to check back on the progress on this. Is this still something you are pursuing?

**Comment by bkuhlmann** [comment]
:information_source: Closing this issue until there is further interest.
