### ISSUE TITLE
does Commit Subject Suffix makes sense?

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#5]
As said in [Github Write good commit messages guide](https://github.com/erlang/otp/wiki/Writing-good-commit-messages#dont):

> Don't end the summary line with a period - it's a title and titles don't end with a period

And I think that is just the opposite what this is enforcing.

**Comment by bkuhlmann** [comment]
Yep, please see the discussion in this [closed issue](https://github.com/bkuhlmann/git-cop/issues/1).

**Comment by Ana06** [comment]
ok... :confused:

**Comment by bkuhlmann** [comment]
Yeah, sorry, but don't forget. You can customize Git Cop however you like. If the defaults are not quite what you want you can change the settings or disable the cop altogether. :)
