### ISSUE TITLE
Add severity levels to all cops.

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#6]
I think it would be great if we had a third option for `:enabled:` in the configuration file: `true`, `false` and `warning`. As there are something you may want to not to enable, but at least make the user aware. :bowtie:

**Comment by bkuhlmann** [comment]
Yeah, that's a good idea. This would be especially handing when Git Cop is used as a Git Hook.

**Comment by bkuhlmann** [comment]
I'm thinking of introducing a severity option to all cops for this work. Something along the lines of the following:

```
severity: info || warn || error
```

This would allow the `enabled` key to not be overloaded.

Thoughts?

**Comment by Ana06** [comment]
@bkuhlmann I like the idea of having it separately :+1: 

BTW, what would be the difference between info and warning? I guess any of them would make the linter fails. :thinking:

**Comment by bkuhlmann** [comment]
Thanks! Yeah, `info` and `warn` would be identical. I'll drop `info`, for now. Best to address the immediate need which is only `warn` and `error`. At some point, these could be color coded as a readability enhancement:

- warn (yellow)
- error (red)

**Comment by bkuhlmann** [comment]
:information_source: The work on this issue is almost done (see [feature branch](https://github.com/bkuhlmann/git-cop/compare/severity?expand=1) for a sneak peek if you want). Had to make structural changes, namely the introduction of specialized reporters, in order to support this work but hope to have this ready for review by this weekend.

**Comment by bkuhlmann** [comment]
This issue has been resolved by this [pull request](https://github.com/bkuhlmann/git-cop/pull/17).
