### ISSUE TITLE
Add Commit Body Present cop.

### ISSUE THREAD

**Issue by Ana06** [bkuhlmann/git-cop#7]
I would like to have a cop that ensure that every commit has a description. I think there is always some more information that can be given.

**Comment by Ana06** [comment]
@bkuhlmann what do you think about having this? :thinking:

**Comment by bkuhlmann** [comment]
Yeah, sounds good to me. I had wanted to add that earlier but decided to hold off and see if there was a need for it. A couple of suggestions, in case you are planning to issue a PR for this:

- A body can only be present if it has content. Content with only whitespace, carriage returns, etc. would be an error.
- It should be disabled by default as some people won't want this.
- There might need to be a minimum number of lines. Example: `minimum: 1`. Can be customized to be higher but 1 would be a safe bet.

**Comment by Ana06** [comment]
@bkuhlmann 

> - A body can only be present if it has content. Content with only whitespace, carriage returns, etc. would be an error.
> - It should be disabled by default as some people won't want this.
> - There might need to be a minimum number of lines. Example: minimum: 1. Can be customized to be higher but 1 would be a safe bet.

Sounds good! 👍 I'll try to send request in the following days

**Comment by bkuhlmann** [comment]
Awesome, thanks. 🙇
